name: k8-app docker images builder

on:
  push:
    branches: [main]
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Image
        run: |
          echo "${{secrets.DOCKER_PASS }}" | docker login -u "adesh0303" --password-stdin
          docker image build -t adesh0303/k8-app:v3 .
          docker push adesh0303/k8-app:v3
